name: Déployer le site Hugo sur GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Vérifier les sous-modules
        run: git submodule update --init --recursive

      - name: Installer Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Construire le site Hugo
        run: hugo --minify

      - name: Ajouter le fichier CNAME
        run: echo "blog.axellelanca.com" > public/CNAME

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          commit_message: "Déploiement automatique par GitHub Actions"
